[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'

[phases.setup]
    nixPkgs = ['nodejs', 'jq']

[phases.build]
    cmds = [
        'npm ci',
        'npm run build' # asegúrate que este comando construye tu app Angular
    ]

[phases.caddy]
    nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'
    nixPkgs = ['caddy']

[phases.fmt]
    dependsOn = ['caddy']
    cmds = ['caddy fmt --overwrite Caddyfile']

[start]
    cmd = '''
    export ANGULAR_OUTPUT_PATH=$(jq -r ".projects[] | .architect.build.options.outputPath" angular.json);
    while ! command -v caddy >/dev/null; do sleep 1; done
    caddy run --config Caddyfile --adapter caddyfile 2>&1
    '''
